#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER ${KC_DB_USER}     WITH ENCRYPTED PASSWORD '${KC_DB_PASSWORD}';
  CREATE USER ${LITELLM_DB_USER} WITH ENCRYPTED PASSWORD '${LITELLM_DB_PASSWORD}';
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE litellm OWNER ${LITELLM_DB_USER};
  CREATE DATABASE kc OWNER ${KC_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="kc" <<-EOSQL
  ALTER SCHEMA public OWNER TO ${KC_DB_USER};
  GRANT ALL ON SCHEMA public TO ${KC_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="litellm" <<-EOSQL
  ALTER SCHEMA public OWNER TO ${LITELLM_DB_USER};
  GRANT ALL ON SCHEMA public TO ${LITELLM_DB_USER};
EOSQL
